services:

  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://IP:3456   # o dominio
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: p4ssw0rd
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET:  # generar clave con el comando "openssl rand -base64 32"
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 1 # Una vez ya registrado cambiar: VIKUNJA_SERVICE_ENABLEREGISTRATION: 0 (en vez de 1) para evitar nuevos registros.
    ports:
      - "8200:3456"
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_USER: vikunja
    volumes:
      - ./db:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s
